# Generated by Django 3.2.8 on 2022-01-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_player_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='survive_time',
            field=models.IntegerField(default=0),
        ),
    ]
